name: Post welcome comment

on:
  push

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - run: echo "Hallo Alfa"
      - run: docker run hello-world
      
      
    
